version: "3"
services:
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile
        container_name: client_cont
        ports:
            - 3005:3000
        volumes:
            - ./client:/var/www/html/client
        depends_on:
            - server

    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        container_name: server_cont
        ports:
            - 5000:5000
        volumes:
            - ./server:/var/www/html/server
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=assignment
            - MYSQL_PORT=3307
        depends_on:
            - database

    database:
        image: mysql:latest
        container_name: database_cont
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=assignment
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
        command: ["--default-authentication-plugin", "mysql_native_password"]

