version: "3"
services:
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend_cont
        ports:
            - 3005:3000
        volumes:
            - ./frontend:/var/www/html/frontend
        depends_on:
            - backend
        networks:
            - front_network

    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend_cont
        ports:
            - 5000:5000
        volumes:
            - ./backend:/var/www/html/backend
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=assignment
            - MYSQL_PORT=3307
        depends_on:
            - database
        networks:
            - back_network

    database:
        image: mysql:latest
        container_name: database_cont
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=assignment
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
        command: ["--default-authentication-plugin", "mysql_native_password"]
        networks:
            - back_network

networks:
    front_network:
        driver: bridge
    back_network:
        driver: bridge